image: marcopeg/gitpod-workspace-postgres:2.5.0

ports:
  - port: 8008
    onOpen: ignore
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.1:DO6k4GCpqhwZcKo+jY9xjQ==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
    - mikestead.dotenv@1.0.1:SSXjr5hZcbqSF7nMIhTNnA==
    - wayou.vscode-todo-highlight@1.0.4:8IqxuxCVol2WnScJc5xVzg==
    