version: '3.7'

services:
  postgres:
    image: postgres:12.3
    restart: always
    volumes:
      - ${HUMBLE_DATA:-./data}/postgres:/var/lib/postgresql/data:consistent
      - ${HUMBLE_DATA:-./data}/backup:/backup:consistent
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

  adminer:
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.middlewares.postgres-playground-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.postgres-playground-redirect.redirectscheme.permanent=true'
      - 'traefik.http.middlewares.postgres-playground-auth.basicauth.usersfile=/basic-auth/.htpasswd'

      - 'traefik.http.routers.postgres-playground.rule=Host(`postgres-playground.${VSCODE_DNS}`)'
      - 'traefik.http.routers.postgres-playground.entrypoints=web'
      - 'traefik.http.routers.postgres-playground.middlewares=postgres-playground-redirect'

      - 'traefik.http.routers.postgres-playground-secure.rule=Host(`postgres-playground.${VSCODE_DNS}`)'
      - 'traefik.http.routers.postgres-playground-secure.entrypoints=websecure'
      - 'traefik.http.routers.postgres-playground-secure.tls=true'
      - 'traefik.http.routers.postgres-playground-secure.tls.certresolver=myresolver'
      - 'traefik.http.routers.postgres-playground-secure.middlewares=postgres-playground-auth'
    image: adminer:4.7
    restart: always
    links:
      - postgres:db

  migrations:
    image: node:12.2-alpine
    volumes:
      - ${HUMBLE_DATA}/migrations/node_modules:/usr/src/app/node_modules:cached
      - ./migrations/package.json:/usr/src/app/package.json:cached
      - ./migrations/package-lock.json:/usr/src/app/package-lock.json:cached
      - ./migrations/index.js:/usr/src/app/index.js:delegated
      - ./migrations/knexfile.js:/usr/src/app/knexfile.js:delegated
      - ./migrations/migrations:/usr/src/app/migrations:delegated
      - ./migrations/seeds:/usr/src/app/seeds:delegated
    working_dir: /usr/src/app
    # user: ${ID_U:-1000}:${ID_G:-1000}
    # stdin_open: true
    # tty: true
    # entrypoint: ["/bin/sh"]
    entrypoint: ['npm', 'run', 'start:compose']
